# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: v2
name: shippingservice
description: A Helm chart for shippingservice
type: application
version: 0.1.0
appVersion: "v0.3.0"
