# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

#################################################################
# Global configuration defaults.
#################################################################
global:
  nodePortPrefixExt: 304
  persistence: {}
#################################################################
# Application configuration defaults.
#################################################################
# application image
# repository: registry.gitlab.com/project-emco/core/emco-base/ # uncomment to override default/inherited repository
# emcoTag: latest # uncomment to override default/inherited emcoTag
image: emco-workflowmgr

pullPolicy: Always
args: ""
command: "./workflowmgr"
workingDir: /opt/emco/workflowmgr

# flag to enable debugging - application support required
debugEnabled: false

# application configuration is via config files

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}


# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 30
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: false

readiness:
  initialDelaySeconds: 10
  periodSeconds: 30
  enabled: false

service:
  type: NodePort
  name: workflowmgr
  portName: workflowmgr-service
  internalPort: 9095
  externalPort: 9095
  nodePort: 95

serviceInternal:
  type: NodePort
  name: workflowmgr
  portName: workflowmgr-status
  internalPort: 9097
  externalPort: 9097
  nodePort: 97

ingress:
  enabled: false

# Configure resource requests and limits
flavor: large
resources:
  small:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 10Mi
  large:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
  unlimited: {}

podAnnotations:
  # The metrics use the same port as the service
  prometheus.io/path: /metrics
  prometheus.io/port: "9095"
  prometheus.io/scrape: "true"
