apiVersion: apps/v1
kind: Deployment
metadata:
  name: right-nginx
  namespace: {{ .Values.Namespace }}
  labels:
    app: tail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tail
  template:
    metadata:
      labels:
        app: tail
    spec:
      containers:
      - name: nginx
        image: rkamudhan/netshoot:v1.0
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        resources:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "500m"
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
