# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: {{ .Values.recommendationservice.type }}
  selector:
    app: recommendationservice
  ports:
	{{- .Values.recommendationservice.ports | toYaml | nindent 2 -}}
