{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation
*/}}
{{- if .Values.global.enableMongoSecret }}
{{- if .Values.global.db.dataEncryptor }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-data-secret
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ include "common.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config.json: {{ mustToJson .Values.global.db.dataEncryptor | b64enc | quote }}
{{- else }}
{{- $dataEncryptor := (dict "providers" (list (dict "aesgcm" (dict "keys" (list (dict "name" "emcoDataKey" "secret" ((default (randAlphaNum 32) $.Values.global.db.dataSecret) | b64enc))))))) }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-data-secret
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ include "common.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config.json: {{ mustToJson $dataEncryptor | b64enc | quote }}
{{- end }}
{{- end -}}
