# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
image:
    repository: <myrepository.example.com>/app/my-custom-httptest-client
    tag: "1.1"
    pullPolicy: Always

server:
    domain: "http://http-service:30083"

service:
    type: ClusterIP
    nameOfPort: webPort
    annotations: {}
    labels: {}
    clusterIP: ""

resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi
