# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.frontend.type }}
  selector:
    app: frontend
  ports:
	{{- .Values.frontend.ports | toYaml | nindent 2 -}}
