# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: {{ .Values.shippingservice.type }}
  selector:
    app: shippingservice
  ports:
	{{- .Values.shippingservice.ports | toYaml | nindent 2 -}}
