# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
httpbinservice:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  server:
    port: 8000
    image:
      repository: docker.io/kennethreitz/httpbin 
      tag: "latest"
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  type: ClusterIP
