apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv-postgress-data
  labels:
    name: gitea-pv-postgress
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/emco/postgresql/data"
