apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv-volume-data
  labels:
    name: gitea-pv-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/emco/gitea/data"
