# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
currencyservice:
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000
  server:
    port: 7000
    image:
      repository: gcr.io/google-samples/microservices-demo/currencyservice
      tag: v0.3.0
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  type: ClusterIP
