# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
paymentservice:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  server:
    port: 50051
    image:
      repository: gcr.io/google-samples/microservices-demo/paymentservice
      tag: v0.3.0
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  type: ClusterIP
