{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Aarna Networks, Inc.
*/}}

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metricscollector
subjects:
- kind: ServiceAccount
  name: metricscollector
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
