{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Aarna Networks, Inc.
*/}}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: metricscollectors.edgemetricscollector.k8splugin.io
spec:
  group: edgemetricscollector.k8splugin.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                agentName:
                  type: string
                metricList:
                  type: array
                  items:
                    type: string
      subresources:
        status: {}
  names:
    kind: MetricsCollector
    plural: metricscollectors
  scope: Namespaced
