{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Aarna Networks, Inc.
*/}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricscollector
  namespace: {{ .Release.Namespace }}
