# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

#################################################################
# Global configuration defaults.
#################################################################
global:
  nodePortPrefixExt: 304
  persistence: {}
#################################################################
# Application configuration defaults.
#################################################################
# application image
repository:
image: emco-ca-certs
imageTag:
pullPolicy: Always
args: ""
command: "./ca-certs"
workingDir: /opt/emco/ca-certs

# flag to enable debugging - application support required
debugEnabled: false

# application configuration is via config files

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}


# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 30
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 10
  periodSeconds: 30

service:
  type: NodePort
  name: ca-certs
  portName: ca-certs-service
  internalPort: 9036 
  externalPort: 9036
  nodePort: 36

serviceInternal:
  type: NodePort
  name: ca-certs
  portName: ca-certs-status
  internalPort: 9037
  externalPort: 9037
  nodePort: 37

ingress:
  enabled: false

# Configure resource requests and limits
flavor: large
resources:
  small:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 10Mi
  large:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
  unlimited: {}
