# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: {{ .Values.paymentservice.type }}
  selector:
    app: paymentservice
  ports:
	{{- .Values.paymentservice.ports | toYaml | nindent 2 -}}
