# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

repository: nst1-08.jf.intel.com/emco/
image: emco-monitor
emcoTag: "latest" # can be overridden with $ helm install --set emcoTag=22.03 emco-monitor (...)

workingDir: /opt/emco/monitor
git:
  enabled: false

noProxyHosts: ""
httpProxy: ""
httpsProxy: ""
