# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: {{ .Values.cartservice.type }}
  selector:
    app: cartservice
  ports:
	{{- .Values.cartservice.ports | toYaml | nindent 2 -}}
