apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-monitor-list
  namespace: {{ .Release.Namespace }}
data:
  gvk.conf: |
      [
        {"Group": "k8s.plugin.opnfv.org", "Version": "v1alpha1", "Kind": "Network", "Resource": "networks" },
        {"Group": "rbac.authorization.k8s.io", "Version": "v1", "Kind": "ClusterRole", "Resource": "clusterroles"},
        {"Group": "cert-manager.io", "Version": "v1", "Kind": "CertificateRequest", "Resource": "certificaterequests"},
        {"Group": "networking.istio.io", "Version": "v1beta1", "Kind": "ProxyConfig", "Resource": "proxyconfigs"},
        {"Group": "cert-manager.io", "Version": "v1", "Kind": "ClusterIssuer", "Resource": "clusterissuers"},
        {"Version": "v1", "Kind": "Secret", "Resource": "secrets"},
        {"Group": "cert-manager.io", "Version": "v1", "Kind": "Certificate", "Resource": "certificates"}
      ]
  
