ProjectName: proj1
ClusterProvider: provider1

# Issuing Cluster
IssuingCluster: issuer1
IssuingClusterConfig: /home/vagrant/git/multicloud-k8s/cluster-configs/config-edge02

# Clsuters
Cluster1: cluster1
KubeConfig1: /home/vagrant/git/multicloud-k8s/cluster-configs/config-edge01
Cluster2: cluster2
KubeConfig2: /home/vagrant/git/multicloud-k8s/cluster-configs/config-edge01
Cluster3: cluster3
KubeConfig3: /home/vagrant/git/multicloud-k8s/cluster-configs/config-edge01
Cluster4: cluster4
KubeConfig4: /home/vagrant/github.com/cluster-configs/cluster-2-config
Cluster5: cluster5
KubeConfig5: /home/vagrant/github.com/cluster-configs/cluster-3-config

# Cluster Label
ClusterLabel: cluster3
GroupLabel1: group1
GroupLabel2: group2

# Cert
CertIntent1: cert1
CertIntent2: cert2
CertIntent3: cert3

# Cluster Issuer
ClusterIssuer: foo
Kind: ClusterIssuer
Group: cert-manager.io

# CSR Info
KeySize: 4096
CommonNamePrefix: foo

# Cluster Group
EdgeClusters: edge
EdgeClusters1: edge1
EdgeClusters2: edge2
RsyncPort: 9031
HostIP: 10.10.10.6

# Logical-Cloud
AdminCloud: default
FooLogicalCloud: foo
BarLogicalCloud: bar
Cluster1Ref: cluster1-ref
FooCloud: foo-ns
BarCloud: bar-ns
