    PackagesPath: output
    ProjectName: proj-anthos
    ClusterProvider: provider-anthos
    ClusterLabel: edge-cluster
    CompositeApp: test-composite-app
    CompositeProfile: test-composite-profile
    GenericPlacementIntent: test-placement-intent
    DeploymentIntent: test-deployment-intent
    Intent: intent
    RsyncPort: 9031
    GacPort: 9033
    OvnPort: 9032
    DtcPort: 9048
    NpsPort: 9038
    GitType: gitea
    GitObj: GitObject
    GitUser:
    GitToken: TOKEN_HERE
    GitRepo:
    GitUrl: URL_HERE
    Branch: main
    Cluster1: acm-cluster
    Cluster1Ref: acm-cluster-ref
    LogicalCloud: lc1
    PrivilegedNamespace: privileged-lc-ns
    StandardNamespace: standard-lc-ns
    ClusterQuota: quota1
    StandardPermission: standard-permission
    PrivilegedPermission1: privileged-permission-primary
    PrivilegedPermission2: privileged-permission-kube-system
    PrivilegedPermission3: privileged-permission-cluster

    Applist:
      - Name: collectd
