# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

#################################################################
# Global configuration defaults.
#################################################################
global:
  nodePortPrefixExt: 304
  persistence: {}
#################################################################
# Application configuration defaults.
#################################################################
# application image
# repository: registry.gitlab.com/project-emco/core/emco-base/ # uncomment to override default/inherited repository
# emcoTag: latest # uncomment to override default/inherited emcoTag
image: emco-its

pullPolicy: Always
command: "./its"
args: ""
workingDir: /opt/emco/its

# flag to enable debugging - application support required
debugEnabled: false

# application configuration is via config files

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}


# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 30
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 10
  periodSeconds: 30

service:
  type: NodePort
  name: its
  portName: its-control
  internalPort: 9040
  externalPort: 9040
  nodePort: 40

serviceInternal:
  type: NodePort
  name: its
  portName: its-service
  internalPort: 9037
  externalPort: 9037
  nodePort: 37

ingress:
  enabled: false

# Configure resource requests and limits
flavor: large
resources:
  small:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 10Mi
  large:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
  unlimited: {}

podAnnotations:
  # The metrics use the same port as the service
  prometheus.io/path: /metrics
  prometheus.io/port: "9037"
  prometheus.io/scrape: "true"
