# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
clientservice:
  image:
    repository: otconap11.sc.intel.com/httpbin-client
    tag: "1.0"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
