# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

#################################################################
# Global configuration defaults.
#################################################################
global:
  nodePortPrefixExt: 304
  persistence: {}
  # repository: registry.gitlab.com/project-emco/core/emco-base/ # uncomment to override default/inherited repository
  # emcoTag: latest # uncomment to override default/inherited emcoTag
#################################################################
# Application configuration defaults.
#################################################################
# application image
image: emco-sample

pullPolicy: Always
command: "./sample"
args: ""
workingDir: /opt/emco/sample

# flag to enable debugging - application support required
debugEnabled: false

# application configuration is via config files

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 30
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 10
  periodSeconds: 30

service:
  type: NodePort
  name: sample
  portName: http
  internalPort: 9024
  externalPort: 9024
  nodePort: 24

serviceInternal:
  type: NodePort
  name: internal
  portName: internal
  internalPort: 9025
  externalPort: 9025
  nodePort: 25

ingress:
  enabled: false

# Configure resource requests and limits
flavor: large
resources:
  small:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 10Mi
  large:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
  unlimited: {}

podAnnotations:
  # The metrics use the same port as the service
  prometheus.io/path: /metrics
  prometheus.io/port: "9024"
  prometheus.io/scrape: "true"
