# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: {{ .Values.emailservice.type }}
  selector:
    app: emailservice
  ports:
	{{- .Values.emailservice.ports | toYaml | nindent 2 -}}
