# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation
clientservice:
  image:
    repository: <docker-registry-url>/mysql-client
    tag: "1.0"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
