# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
recommendationservice:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  server:
    port: 8080
    productcatalogserviceport: 3550
    image:
      repository: gcr.io/google-samples/microservices-demo/recommendationservice
      tag: v0.3.0
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 450Mi
      requests:
        cpu: 100m
        memory: 220Mi
  type: ClusterIP
