# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

apiVersion: v2
description: EMCO All-In-One Package
name: emco
type: application
version: 1.0.2

dependencies:
  - name: emco-db
    version: ~1.x-0
    repository: 'file://../emco-db'
  - name: emco-tools
    version: ~1.x-0
    repository: 'file://../emco-tools'
  - name: emco-services
    version: "1.0.2"
    repository: 'file://../emco-services'
