// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2020 Intel Corporation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.11.4
// source: installapp.proto

package installapp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event type for the event
type EventType int32

const (
	EventType_INSTANTIATE EventType = 0
	EventType_TERMINATE   EventType = 1
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "INSTANTIATE",
		1: "TERMINATE",
	}
	EventType_value = map[string]int32{
		"INSTANTIATE": 0,
		"TERMINATE":   1,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_installapp_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_installapp_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{0}
}

type InstallAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContext string `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
}

func (x *InstallAppRequest) Reset() {
	*x = InstallAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppRequest) ProtoMessage() {}

func (x *InstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_installapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppRequest.ProtoReflect.Descriptor instead.
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{0}
}

func (x *InstallAppRequest) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

type InstallAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContextInstalled      bool   `protobuf:"varint,1,opt,name=app_context_installed,json=appContextInstalled,proto3" json:"app_context_installed,omitempty"`
	AppContextInstallMessage string `protobuf:"bytes,2,opt,name=app_context_install_message,json=appContextInstallMessage,proto3" json:"app_context_install_message,omitempty"`
}

func (x *InstallAppResponse) Reset() {
	*x = InstallAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppResponse) ProtoMessage() {}

func (x *InstallAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_installapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppResponse.ProtoReflect.Descriptor instead.
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{1}
}

func (x *InstallAppResponse) GetAppContextInstalled() bool {
	if x != nil {
		return x.AppContextInstalled
	}
	return false
}

func (x *InstallAppResponse) GetAppContextInstallMessage() string {
	if x != nil {
		return x.AppContextInstallMessage
	}
	return ""
}

type UninstallAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContext string `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
}

func (x *UninstallAppRequest) Reset() {
	*x = UninstallAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installapp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UninstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallAppRequest) ProtoMessage() {}

func (x *UninstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_installapp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallAppRequest.ProtoReflect.Descriptor instead.
func (*UninstallAppRequest) Descriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{2}
}

func (x *UninstallAppRequest) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

type UninstallAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContextUninstalled      bool   `protobuf:"varint,1,opt,name=app_context_uninstalled,json=appContextUninstalled,proto3" json:"app_context_uninstalled,omitempty"`
	AppContextUninstallMessage string `protobuf:"bytes,2,opt,name=app_context_uninstall_message,json=appContextUninstallMessage,proto3" json:"app_context_uninstall_message,omitempty"`
}

func (x *UninstallAppResponse) Reset() {
	*x = UninstallAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installapp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UninstallAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallAppResponse) ProtoMessage() {}

func (x *UninstallAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_installapp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallAppResponse.ProtoReflect.Descriptor instead.
func (*UninstallAppResponse) Descriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{3}
}

func (x *UninstallAppResponse) GetAppContextUninstalled() bool {
	if x != nil {
		return x.AppContextUninstalled
	}
	return false
}

func (x *UninstallAppResponse) GetAppContextUninstallMessage() string {
	if x != nil {
		return x.AppContextUninstallMessage
	}
	return ""
}

type ReadAppContextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContext string `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
}

func (x *ReadAppContextRequest) Reset() {
	*x = ReadAppContextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installapp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAppContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAppContextRequest) ProtoMessage() {}

func (x *ReadAppContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_installapp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAppContextRequest.ProtoReflect.Descriptor instead.
func (*ReadAppContextRequest) Descriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{4}
}

func (x *ReadAppContextRequest) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

type ReadAppContextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContextReadSuccessful bool   `protobuf:"varint,1,opt,name=app_context_read_successful,json=appContextReadSuccessful,proto3" json:"app_context_read_successful,omitempty"`
	AppContextReadMessage    string `protobuf:"bytes,2,opt,name=app_context_read_message,json=appContextReadMessage,proto3" json:"app_context_read_message,omitempty"`
}

func (x *ReadAppContextResponse) Reset() {
	*x = ReadAppContextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installapp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAppContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAppContextResponse) ProtoMessage() {}

func (x *ReadAppContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_installapp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAppContextResponse.ProtoReflect.Descriptor instead.
func (*ReadAppContextResponse) Descriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAppContextResponse) GetAppContextReadSuccessful() bool {
	if x != nil {
		return x.AppContextReadSuccessful
	}
	return false
}

func (x *ReadAppContextResponse) GetAppContextReadMessage() string {
	if x != nil {
		return x.AppContextReadMessage
	}
	return ""
}

type DependentAppContextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContext    string    `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	DepAppContext string    `protobuf:"bytes,2,opt,name=dep_app_context,json=depAppContext,proto3" json:"dep_app_context,omitempty"`
	EventType     EventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=EventType" json:"event_type,omitempty"`
}

func (x *DependentAppContextRequest) Reset() {
	*x = DependentAppContextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installapp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependentAppContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentAppContextRequest) ProtoMessage() {}

func (x *DependentAppContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_installapp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentAppContextRequest.ProtoReflect.Descriptor instead.
func (*DependentAppContextRequest) Descriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{6}
}

func (x *DependentAppContextRequest) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *DependentAppContextRequest) GetDepAppContext() string {
	if x != nil {
		return x.DepAppContext
	}
	return ""
}

func (x *DependentAppContextRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_INSTANTIATE
}

type DependentAppContextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContextDependentSuccessful bool   `protobuf:"varint,1,opt,name=app_context_dependent_successful,json=appContextDependentSuccessful,proto3" json:"app_context_dependent_successful,omitempty"`
	AppContextDependentMessage    string `protobuf:"bytes,2,opt,name=app_context_dependent_message,json=appContextDependentMessage,proto3" json:"app_context_dependent_message,omitempty"`
}

func (x *DependentAppContextResponse) Reset() {
	*x = DependentAppContextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_installapp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependentAppContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentAppContextResponse) ProtoMessage() {}

func (x *DependentAppContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_installapp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentAppContextResponse.ProtoReflect.Descriptor instead.
func (*DependentAppContextResponse) Descriptor() ([]byte, []int) {
	return file_installapp_proto_rawDescGZIP(), []int{7}
}

func (x *DependentAppContextResponse) GetAppContextDependentSuccessful() bool {
	if x != nil {
		return x.AppContextDependentSuccessful
	}
	return false
}

func (x *DependentAppContextResponse) GetAppContextDependentMessage() string {
	if x != nil {
		return x.AppContextDependentMessage
	}
	return ""
}

var File_installapp_proto protoreflect.FileDescriptor

var file_installapp_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x34, 0x0a, 0x11, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70,
	0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x12, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x32, 0x0a, 0x15, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13,
	0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x65, 0x64, 0x12, 0x3d, 0x0a, 0x1b, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x36, 0x0a, 0x13, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x14, 0x55,
	0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x41, 0x0a, 0x1d, 0x61,
	0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x1a, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x55, 0x6e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x38,
	0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70,
	0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x61,
	0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x1b, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66,
	0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x18, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x61, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66,
	0x75, 0x6c, 0x12, 0x37, 0x0a, 0x18, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x1a,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70,
	0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x64,
	0x65, 0x70, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x29, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0xa9,
	0x01, 0x0a, 0x1b, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x20, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x64, 0x65,
	0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66,
	0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1d, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x12, 0x41, 0x0a, 0x1d, 0x61, 0x70, 0x70, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1a,
	0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x2b, 0x0a, 0x09, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x53, 0x54, 0x41,
	0x4e, 0x54, 0x49, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x45, 0x52, 0x4d,
	0x49, 0x4e, 0x41, 0x54, 0x45, 0x10, 0x01, 0x32, 0x9d, 0x02, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x61, 0x70, 0x70, 0x12, 0x37, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x41, 0x70, 0x70, 0x12, 0x12, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x0c, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x12,
	0x14, 0x2e, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x55, 0x6e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43,
	0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x16, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x41,
	0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74,
	0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x2e, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6c, 0x6c, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_installapp_proto_rawDescOnce sync.Once
	file_installapp_proto_rawDescData = file_installapp_proto_rawDesc
)

func file_installapp_proto_rawDescGZIP() []byte {
	file_installapp_proto_rawDescOnce.Do(func() {
		file_installapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_installapp_proto_rawDescData)
	})
	return file_installapp_proto_rawDescData
}

var file_installapp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_installapp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_installapp_proto_goTypes = []interface{}{
	(EventType)(0),                      // 0: EventType
	(*InstallAppRequest)(nil),           // 1: InstallAppRequest
	(*InstallAppResponse)(nil),          // 2: InstallAppResponse
	(*UninstallAppRequest)(nil),         // 3: UninstallAppRequest
	(*UninstallAppResponse)(nil),        // 4: UninstallAppResponse
	(*ReadAppContextRequest)(nil),       // 5: ReadAppContextRequest
	(*ReadAppContextResponse)(nil),      // 6: ReadAppContextResponse
	(*DependentAppContextRequest)(nil),  // 7: DependentAppContextRequest
	(*DependentAppContextResponse)(nil), // 8: DependentAppContextResponse
}
var file_installapp_proto_depIdxs = []int32{
	0, // 0: DependentAppContextRequest.event_type:type_name -> EventType
	1, // 1: installapp.InstallApp:input_type -> InstallAppRequest
	3, // 2: installapp.UninstallApp:input_type -> UninstallAppRequest
	5, // 3: installapp.ReadAppContext:input_type -> ReadAppContextRequest
	7, // 4: installapp.DependentAppContext:input_type -> DependentAppContextRequest
	2, // 5: installapp.InstallApp:output_type -> InstallAppResponse
	4, // 6: installapp.UninstallApp:output_type -> UninstallAppResponse
	6, // 7: installapp.ReadAppContext:output_type -> ReadAppContextResponse
	8, // 8: installapp.DependentAppContext:output_type -> DependentAppContextResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_installapp_proto_init() }
func file_installapp_proto_init() {
	if File_installapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_installapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installapp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UninstallAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installapp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UninstallAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installapp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAppContextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installapp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAppContextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installapp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DependentAppContextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_installapp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DependentAppContextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_installapp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_installapp_proto_goTypes,
		DependencyIndexes: file_installapp_proto_depIdxs,
		EnumInfos:         file_installapp_proto_enumTypes,
		MessageInfos:      file_installapp_proto_msgTypes,
	}.Build()
	File_installapp_proto = out.File
	file_installapp_proto_rawDesc = nil
	file_installapp_proto_goTypes = nil
	file_installapp_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InstallappClient is the client API for Installapp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InstallappClient interface {
	// Sync
	InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error)
	UninstallApp(ctx context.Context, in *UninstallAppRequest, opts ...grpc.CallOption) (*UninstallAppResponse, error)
	ReadAppContext(ctx context.Context, in *ReadAppContextRequest, opts ...grpc.CallOption) (*ReadAppContextResponse, error)
	DependentAppContext(ctx context.Context, in *DependentAppContextRequest, opts ...grpc.CallOption) (*DependentAppContextResponse, error)
}

type installappClient struct {
	cc grpc.ClientConnInterface
}

func NewInstallappClient(cc grpc.ClientConnInterface) InstallappClient {
	return &installappClient{cc}
}

func (c *installappClient) InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error) {
	out := new(InstallAppResponse)
	err := c.cc.Invoke(ctx, "/installapp/InstallApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installappClient) UninstallApp(ctx context.Context, in *UninstallAppRequest, opts ...grpc.CallOption) (*UninstallAppResponse, error) {
	out := new(UninstallAppResponse)
	err := c.cc.Invoke(ctx, "/installapp/UninstallApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installappClient) ReadAppContext(ctx context.Context, in *ReadAppContextRequest, opts ...grpc.CallOption) (*ReadAppContextResponse, error) {
	out := new(ReadAppContextResponse)
	err := c.cc.Invoke(ctx, "/installapp/ReadAppContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installappClient) DependentAppContext(ctx context.Context, in *DependentAppContextRequest, opts ...grpc.CallOption) (*DependentAppContextResponse, error) {
	out := new(DependentAppContextResponse)
	err := c.cc.Invoke(ctx, "/installapp/DependentAppContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstallappServer is the server API for Installapp service.
type InstallappServer interface {
	// Sync
	InstallApp(context.Context, *InstallAppRequest) (*InstallAppResponse, error)
	UninstallApp(context.Context, *UninstallAppRequest) (*UninstallAppResponse, error)
	ReadAppContext(context.Context, *ReadAppContextRequest) (*ReadAppContextResponse, error)
	DependentAppContext(context.Context, *DependentAppContextRequest) (*DependentAppContextResponse, error)
}

// UnimplementedInstallappServer can be embedded to have forward compatible implementations.
type UnimplementedInstallappServer struct {
}

func (*UnimplementedInstallappServer) InstallApp(context.Context, *InstallAppRequest) (*InstallAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallApp not implemented")
}
func (*UnimplementedInstallappServer) UninstallApp(context.Context, *UninstallAppRequest) (*UninstallAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UninstallApp not implemented")
}
func (*UnimplementedInstallappServer) ReadAppContext(context.Context, *ReadAppContextRequest) (*ReadAppContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAppContext not implemented")
}
func (*UnimplementedInstallappServer) DependentAppContext(context.Context, *DependentAppContextRequest) (*DependentAppContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DependentAppContext not implemented")
}

func RegisterInstallappServer(s *grpc.Server, srv InstallappServer) {
	s.RegisterService(&_Installapp_serviceDesc, srv)
}

func _Installapp_InstallApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallappServer).InstallApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/installapp/InstallApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallappServer).InstallApp(ctx, req.(*InstallAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Installapp_UninstallApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallappServer).UninstallApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/installapp/UninstallApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallappServer).UninstallApp(ctx, req.(*UninstallAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Installapp_ReadAppContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAppContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallappServer).ReadAppContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/installapp/ReadAppContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallappServer).ReadAppContext(ctx, req.(*ReadAppContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Installapp_DependentAppContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependentAppContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallappServer).DependentAppContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/installapp/DependentAppContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallappServer).DependentAppContext(ctx, req.(*DependentAppContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Installapp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "installapp",
	HandlerType: (*InstallappServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallApp",
			Handler:    _Installapp_InstallApp_Handler,
		},
		{
			MethodName: "UninstallApp",
			Handler:    _Installapp_UninstallApp_Handler,
		},
		{
			MethodName: "ReadAppContext",
			Handler:    _Installapp_ReadAppContext_Handler,
		},
		{
			MethodName: "DependentAppContext",
			Handler:    _Installapp_DependentAppContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "installapp.proto",
}
